name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: bash build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
